# Dockerfile.frontend
FROM node:18-alpine AS prod

WORKDIR /app

COPY package*.json ./

EXPOSE 3000

RUN npm install

COPY . .

RUN npm run build

ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

CMD [ "npm", "run", "start" ]