version: "3.8"
services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: nextjs
    volumes:
      - /app
      - /node_modules
    ports:
      - "3000:3000"
    restart: always
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/ssl:/etc/nginx/ssl:ro
      - nginx_cache:/var/cache/nginx
    user: "nginxuser"
    restart: always
volumes:
  nginx_cache:
