# docker-compose.yml
# version: "3.8"
# services:
#   frontend:
#     build:
#       context: .
#       dockerfile: Dockerfile.frontend
#     volumes:
#       - /app
#       - /node_modules
#     ports:
#       - 3000:3000

#   nginx:
#     build:
#       context: ./nginx
#       dockerfile: Dockerfile.nginx
#     container_name: nginx
#     ports:
#       - "80:80"
#       - "443:443"
#     volumes:
#       - /etc/ssl:/etc/nginx/ssl:ro
#     restart: always

  version: "3.8"
    services:
      nextjs:
        build:
          context: .
          dockerfile: Dockerfile.frontend
        volumes:
          - /app
          - /node_modules
        ports:
          - "3000:3000"
        restart: always
        
      nginx:
        build:
          context: .
          dockerfile: Dockerfile.nginx
        container_name: nginx
        ports:
          - "80:80"
          - "443:443"
        volumes:
          - /etc/ssl:/etc/nginx/ssl:ro
        restart: always