import type { Metadata } from "next";
import { Adamina, Inter } from "next/font/google";
import "./globals.css";
import { TheHeader } from "@/components/TheHeader";

const adamina = Adamina({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Personal Project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <TheHeader />
        <main className={adamina.className}>{children}</main>
      </body>
    </html>
  );
}
